[package]
name = "AFE4404"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "example",
]

[build-dependencies]
codegen = { version = "0.2.0" }

[dependencies]
embedded-hal = { version = "1.0.0-alpha.8" }
modular-bitfield = { version = "0.11.2" }